import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import 'bootstrap/dist/css/bootstrap.min.css';

const Home: NextPage = () => {
  
  
  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="relative h-48 w-96 float-right">
          <div className="absolute top-2 right- h-18 w-18 float-right">
            <ConnectButton showBalance={{
              smallScreen: false,
              largeScreen: true,
            }}
            />
          </div>
        </div>

        
        

        





      </main >
    </div >
  );
};

export default Home;
